doctrine:
  dbal:
    connections:
      ispec_default:
        driver: pdo_sqlite
        path: '%dwo_ispac_sqlite_path%'

  orm:
    entity_managers:
      ispec_default:
        connection: ispec_default
        mappings:
          DwoIspecReaderBundle:
            mapping: true
            type: yml
            dir: 'Resources/config/doctrine_mapping'
            prefix: 'Dwo\IspecReaderBundle\Entity'
